---
# tasks file for balancer
#

- name: Open port 80 on RedHat
  firewalld:
          port: 80/tcp
          permanent: yes
          state: enabled
  notify:
      - Reload firewalld
  when: ansible_os_family == "RedHat"


