---
# tasks file for docker

- name: Remove docker if installed from CentOS repo
  yum:
          name:
            - docker
            - docker-client
            - docker-client-latest
            - docker-common
            - docker-latest
            - docker-latest-logrotate
            - docker-logrotate
            - docker-engine
          state: removed
  environment: "{{ proxy }}"

- name: Install required packages
  yum:
          name: " {{ item }}"
          state: latest
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2      
  environment: "{{ proxy }}"

- name: Add docker repo
  get_url:
          url: https://download.docker.com/linux/centos/docker-ce.repo
          dest: /etc/yum.repos.d/docer-ce.repo
  environment: "{{ proxy }}"

- name: Enable Docker Edge repo
  ini_file:
          dest: /etc/yum.repos.d/docer-ce.repo
          section: 'docker-ce-edge'
          option: enabled
          value: 0

- name: Enable Docker Test repo
  ini_file:
          dest: /etc/yum.repos.d/docer-ce.repo
          section: 'docker-ce-test'
          option: enabled
          value: 0

- name: Install Docker
  package:
          name: docker-ce
          state: latest
  environment: "{{ proxy }}"

- name: Create docker.service.d directory
  file:
          path: /etc/systemd/system/docker.service.d
          state: directory

- name: Proxy docker
  template:
          src: templates/http-proxy.conf.j2
          dest: /etc/systemd/system/docker.service.d/http-proxy.conf

- name: Start Docker service
  service:
          name: docker
          state: started
          enabled: yes
          
