---
# tasks file for docke

- name: Install docker on Centos
  include_tasks:
    file: install_docker_Centos.yml 
  when:
    - ansible_facts['distribution'] == "CentOS"

- name: Install docker on Debian
  include_tasks:
    file: install_docker_Debian.yml
  when:
    - ansible_facts['distribution'] == "Debian"

